apiVersion: v1
kind: Service
metadata:
  name: weather-ml-service
spec:
  type: NodePort
  selector:
    app: weather-ml
  ports:
    - port: 80
      targetPort: 80
      nodePort: 5000




