apiVersion: v1
kind: Service
metadata:
  name: weather-ml-service
spec:
  type: NodePort
  selector:
    app: weather-ml
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
      protocol: TCP
